### ISSUE TITLE
No space after `version`?

### ISSUE THREAD

**Issue by yebblies** [Hackerpilot/dfmt#40]
Phobos is close to 50/50 on this issue, although it leans a little toward no space.
```
~/d/phobos$ git grep "version(" | wc -l
582
~/d/phobos$ git grep "version (" | wc -l
504
```

dfmt currently spaces version but not extern.

**Comment by Hackerpilot** [comment]
I'm going to go with "yes", mostly because I think that's the correct color for the bike shed and I'm the one painting it.

**Comment by CyberShadow** [comment]
> the correct color for the bike shed

How about polka dots?

I'd like to contribute the following suggestion:

If the version statement is enclosing a single statement on the same line, it shouldn't have a space, because it looks like a keyword:

    version(Windows) import core.sys.windows.windows;

If it is enclosing a statement on another line, it should have a space, because it looks like an `if` block:

    version (Windows)
    {
        import core.sys.windows.windows;
        import std.windows.syserror;
    }

The same idea can be applied to scope blocks.

> Phobos is close to 50/50 on this issue

I wonder if there's any correlation with whether it encloses a single statement on the same line.
